language: python
python:
  - 3.7

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest tests/test_datasets.py

# We tell Travis to use a token to deploy the master branch of our repo on Pypi.
# This chunk of code is the one that will automatically build and upload the library.
deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: master